service: vcard-csv-converter
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  converter:
    handler: handler.converter
    events:
      - httpApi:
          path: /
          method: post

plugins:
  - serverless-python-requirements
  - serverless-offline
